$LOAD_PATH << File.expand_path('./lib')
require 'rake/testtask'

Rake::TestTask.new do |t| 
  t.libs << 'lib'
  t.libs << 'test'
  t.test_files = FileList['test/lib/*_spec.rb']
  t.verbose = true
end

task :console do
  require 'irb'
  require 'irb/completion'
  ARGV.clear
  IRB.start
end

namespace :db do
  desc 'creates the database that is needed'
  task :create do
    system('createdb beer_reviews')
  end
end

task :default => :test
