$LOAD_PATH << File.expand_path('./lib')
task :console do
  require 'irb'
  require 'irb/completion'
  ARGV.clear
  IRB.start
end

namespace :db do
  desc 'creates the database that is needed'
  task :create do
    system('createdb beer_reviews')
  end
end
